---
http_interactions:
- request:
    method: post
    uri: https://api.helium.com/v1/script
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"name":"script.lua","contents":"LS0gVGVzdCBTY3JpcHQ="},"type":"script"}}'
    headers:
      User-Agent:
      - helium-ruby
      Authorization:
      - "<API KEY>"
      Accept:
      - application/json
      Content-Type:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Access-Control-Allow-Headers:
      - Origin, Content-Type, Accept, Authorization, Cache-Control, Last-Event-ID
      Access-Control-Allow-Origin:
      - "*"
      Airship-Quip:
      - 'WARNING: ulimit -n is 1024'
      Airship-Trace:
      - b13,b12,b11,b10,b09,b08,b07,b06,b05,b04,b03,c03,c04,d04,e05,f06,g07,g08,h10,i12,l13,m16,n16,n11,p11
      Content-Type:
      - application/json;charset=utf8
      Date:
      - Wed, 19 Apr 2017 19:47:30 GMT
      Location:
      - "/v1/script/f8f7c4b6-0d6d-4803-bc54-54e893d88737"
      Server:
      - Warp/3.2.7
      Content-Length:
      - '354'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"name":"script.lua"},"relationships":{"package":{"data":[]},"metadata":{"data":{"id":"f8f7c4b6-0d6d-4803-bc54-54e893d88737","type":"metadata"}}},"id":"f8f7c4b6-0d6d-4803-bc54-54e893d88737","meta":{"created":"2017-04-19T19:47:30.397115Z","digest":"106505101da9e8d279dc688ec1a2cda647debda8d0112553885add44ba039391"},"type":"script"}}'
    http_version: '1.1'
    adapter_metadata:
      effective_url: https://api.helium.com/v1/script
  recorded_at: Wed, 19 Apr 2017 19:47:30 GMT
- request:
    method: post
    uri: https://api.helium.com/v1/library
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"name":"lib.lua","contents":"LS0gVGVzdCBMaWJyYXJ5"},"type":"library"}}'
    headers:
      User-Agent:
      - helium-ruby
      Authorization:
      - "<API KEY>"
      Accept:
      - application/json
      Content-Type:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Access-Control-Allow-Headers:
      - Origin, Content-Type, Accept, Authorization, Cache-Control, Last-Event-ID
      Access-Control-Allow-Origin:
      - "*"
      Airship-Quip:
      - javascript doesn't have integers
      Airship-Trace:
      - b13,b12,b11,b10,b09,b08,b07,b06,b05,b04,b03,c03,c04,d04,e05,f06,g07,g08,h10,i12,l13,m16,n16,n11,p11
      Content-Type:
      - application/json;charset=utf8
      Date:
      - Wed, 19 Apr 2017 19:47:30 GMT
      Location:
      - "/v1/library/0f6eac7d-ce95-48bf-ae55-f0fd8361377f"
      Server:
      - Warp/3.2.7
      Content-Length:
      - '352'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"name":"lib.lua"},"relationships":{"package":{"data":[]},"metadata":{"data":{"id":"0f6eac7d-ce95-48bf-ae55-f0fd8361377f","type":"metadata"}}},"id":"0f6eac7d-ce95-48bf-ae55-f0fd8361377f","meta":{"created":"2017-04-19T19:47:30.479138Z","digest":"500800f8193f61c59a5e1a085971a23a7bc2473529fddf9cdd46b48096f387f3"},"type":"library"}}'
    http_version: '1.1'
    adapter_metadata:
      effective_url: https://api.helium.com/v1/library
  recorded_at: Wed, 19 Apr 2017 19:47:30 GMT
- request:
    method: post
    uri: https://api.helium.com/v1/package
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"name":"test package"},"type":"package","relationships":{"script":{"data":{"id":"f8f7c4b6-0d6d-4803-bc54-54e893d88737","type":"script"}},"library":{"data":[{"id":"0f6eac7d-ce95-48bf-ae55-f0fd8361377f","type":"library"}]}}}}'
    headers:
      User-Agent:
      - helium-ruby
      Authorization:
      - "<API KEY>"
      Accept:
      - application/json
      Content-Type:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Access-Control-Allow-Headers:
      - Origin, Content-Type, Accept, Authorization, Cache-Control, Last-Event-ID
      Access-Control-Allow-Origin:
      - "*"
      Airship-Quip:
      - "$300,000 worth of cows"
      Airship-Trace:
      - b13,b12,b11,b10,b09,b08,b07,b06,b05,b04,b03,c03,c04,d04,e05,f06,g07,g08,h10,i12,l13,m16,n16,n11,p11
      Content-Type:
      - application/json;charset=utf8
      Date:
      - Wed, 19 Apr 2017 19:47:30 GMT
      Location:
      - "/v1/package/4f7fa579-f6b3-4ef4-beb5-dbb59dd35555"
      Server:
      - Warp/3.2.7
      Content-Length:
      - '442'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"name":null},"relationships":{"script":{"data":{"id":"f8f7c4b6-0d6d-4803-bc54-54e893d88737","type":"script"}},"library":{"data":[{"id":"0f6eac7d-ce95-48bf-ae55-f0fd8361377f","type":"library"}]},"sensor-package":{"data":[]},"metadata":{"data":{"id":"4f7fa579-f6b3-4ef4-beb5-dbb59dd35555","type":"metadata"}}},"id":"4f7fa579-f6b3-4ef4-beb5-dbb59dd35555","meta":{"created":"2017-04-19T19:47:30.556733Z"},"type":"package"}}'
    http_version: '1.1'
    adapter_metadata:
      effective_url: https://api.helium.com/v1/package
  recorded_at: Wed, 19 Apr 2017 19:47:30 GMT
- request:
    method: get
    uri: https://api.helium.com/v1/package/4f7fa579-f6b3-4ef4-beb5-dbb59dd35555
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      User-Agent:
      - helium-ruby
      Authorization:
      - "<API KEY>"
      Accept:
      - application/json
      Content-Type:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Origin, Content-Type, Accept, Authorization, Cache-Control, Last-Event-ID
      Access-Control-Allow-Origin:
      - "*"
      Airship-Quip:
      - shut it down
      Airship-Trace:
      - b13,b12,b11,b10,b09,b08,b07,b06,b05,b04,b03,c03,c04,d04,e05,f06,g07,g08,h10,i12,l13,m16,n16,o16,o17,o18
      Content-Type:
      - application/json;charset=utf8
      Date:
      - Wed, 19 Apr 2017 19:47:30 GMT
      Server:
      - Warp/3.2.7
      Content-Length:
      - '442'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"name":null},"relationships":{"script":{"data":{"id":"f8f7c4b6-0d6d-4803-bc54-54e893d88737","type":"script"}},"library":{"data":[{"id":"0f6eac7d-ce95-48bf-ae55-f0fd8361377f","type":"library"}]},"sensor-package":{"data":[]},"metadata":{"data":{"id":"4f7fa579-f6b3-4ef4-beb5-dbb59dd35555","type":"metadata"}}},"id":"4f7fa579-f6b3-4ef4-beb5-dbb59dd35555","meta":{"created":"2017-04-19T19:47:30.556733Z"},"type":"package"}}'
    http_version: '1.1'
    adapter_metadata:
      effective_url: https://api.helium.com/v1/package/4f7fa579-f6b3-4ef4-beb5-dbb59dd35555
  recorded_at: Wed, 19 Apr 2017 19:47:30 GMT
- request:
    method: delete
    uri: https://api.helium.com/v1/package/4f7fa579-f6b3-4ef4-beb5-dbb59dd35555
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      User-Agent:
      - helium-ruby
      Authorization:
      - "<API KEY>"
      Accept:
      - application/json
      Content-Type:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 204
      message: No Content
    headers:
      Access-Control-Allow-Headers:
      - Origin, Content-Type, Accept, Authorization, Cache-Control, Last-Event-ID
      Access-Control-Allow-Origin:
      - "*"
      Airship-Quip:
      - 'WARNING: ulimit -n is 1024'
      Airship-Trace:
      - b13,b12,b11,b10,b09,b08,b07,b06,b05,b04,b03,c03,c04,d04,e05,f06,g07,g08,h10,i12,l13,m16,m20,o20
      Date:
      - Wed, 19 Apr 2017 19:47:30 GMT
      Server:
      - Warp/3.2.7
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ''
    http_version: '1.1'
    adapter_metadata:
      effective_url: https://api.helium.com/v1/package/4f7fa579-f6b3-4ef4-beb5-dbb59dd35555
  recorded_at: Wed, 19 Apr 2017 19:47:30 GMT
- request:
    method: delete
    uri: https://api.helium.com/v1/script/f8f7c4b6-0d6d-4803-bc54-54e893d88737
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      User-Agent:
      - helium-ruby
      Authorization:
      - "<API KEY>"
      Accept:
      - application/json
      Content-Type:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 204
      message: No Content
    headers:
      Access-Control-Allow-Headers:
      - Origin, Content-Type, Accept, Authorization, Cache-Control, Last-Event-ID
      Access-Control-Allow-Origin:
      - "*"
      Airship-Quip:
      - evacuation not done in time
      Airship-Trace:
      - b13,b12,b11,b10,b09,b08,b07,b06,b05,b04,b03,c03,c04,d04,e05,f06,g07,g08,h10,i12,l13,m16,m20,o20
      Date:
      - Wed, 19 Apr 2017 19:47:30 GMT
      Server:
      - Warp/3.2.7
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ''
    http_version: '1.1'
    adapter_metadata:
      effective_url: https://api.helium.com/v1/script/f8f7c4b6-0d6d-4803-bc54-54e893d88737
  recorded_at: Wed, 19 Apr 2017 19:47:30 GMT
- request:
    method: delete
    uri: https://api.helium.com/v1/library/0f6eac7d-ce95-48bf-ae55-f0fd8361377f
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      User-Agent:
      - helium-ruby
      Authorization:
      - "<API KEY>"
      Accept:
      - application/json
      Content-Type:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 204
      message: No Content
    headers:
      Access-Control-Allow-Headers:
      - Origin, Content-Type, Accept, Authorization, Cache-Control, Last-Event-ID
      Access-Control-Allow-Origin:
      - "*"
      Airship-Quip:
      - RB_GC_GUARD
      Airship-Trace:
      - b13,b12,b11,b10,b09,b08,b07,b06,b05,b04,b03,c03,c04,d04,e05,f06,g07,g08,h10,i12,l13,m16,m20,o20
      Date:
      - Wed, 19 Apr 2017 19:47:30 GMT
      Server:
      - Warp/3.2.7
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: ''
    http_version: '1.1'
    adapter_metadata:
      effective_url: https://api.helium.com/v1/library/0f6eac7d-ce95-48bf-ae55-f0fd8361377f
  recorded_at: Wed, 19 Apr 2017 19:47:30 GMT
recorded_with: VCR 3.0.3
