---
http_interactions:
- request:
    method: get
    uri: https://api.helium.com/v1/element/56618098-5145-445c-a6db-805eaf37ff51
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      User-Agent:
      - helium-ruby
      Accept:
      - application/json
      Content-Type:
      - application/json
      Authorization:
      - "<API KEY>"
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Origin, Content-Type, Accept, Authorization
      Access-Control-Allow-Origin:
      - "*"
      Airship-Quip:
      - "$300,000 worth of cows"
      Airship-Trace:
      - b13,b12,b11,b10,b09,b08,b07,b06,b05,b04,b03,c03,c04,d04,e05,f06,g07,g08,h10,i12,l13,m16,n16,o16,o17,o18
      Content-Type:
      - application/json
      Date:
      - Mon, 21 Nov 2016 17:31:57 GMT
      Server:
      - Warp/3.2.7
      Content-Length:
      - '469'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"name":"SF Office"},"relationships":{"device-configuration":{"data":[{"id":"85a9bbf9-0ff7-4678-b071-03342b6c7f91","type":"device-configuration"}]},"metadata":{"data":{"id":"56618098-5145-445c-a6db-805eaf37ff51","type":"metadata"}},"sensor":{"data":[]}},"id":"56618098-5145-445c-a6db-805eaf37ff51","meta":{"mac":"6081f9fffe00029e","created":"2016-04-27T18:19:06.520815Z","last-seen":null,"updated":"2016-11-18T01:05:34.693805Z"},"type":"element"}}'
    http_version: '1.1'
    adapter_metadata:
      effective_url: https://api.helium.com/v1/element/56618098-5145-445c-a6db-805eaf37ff51
  recorded_at: Mon, 21 Nov 2016 17:31:58 GMT
- request:
    method: get
    uri: https://api.helium.com/v1/element/56618098-5145-445c-a6db-805eaf37ff51/device-configuration
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      User-Agent:
      - helium-ruby
      Accept:
      - application/json
      Content-Type:
      - application/json
      Authorization:
      - "<API KEY>"
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Origin, Content-Type, Accept, Authorization
      Access-Control-Allow-Origin:
      - "*"
      Airship-Quip:
      - "$300,000 worth of cows"
      Airship-Trace:
      - b13,b12,b11,b10,b09,b08,b07,b06,b05,b04,b03,c03,c04,d04,e05,f06,g07,g08,h10,i12,l13,m16,n16,o16,o17,o18
      Content-Type:
      - application/json
      Date:
      - Mon, 21 Nov 2016 17:31:58 GMT
      Server:
      - Warp/3.2.7
      Content-Length:
      - '358'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"data":[{"attributes":{},"relationships":{"device":{"data":{"id":"56618098-5145-445c-a6db-805eaf37ff51","type":"element"}},"configuration":{"data":{"id":"461b1e38-6fc2-423b-974a-ae6f504c43a1","type":"configuration"}}},"id":"85a9bbf9-0ff7-4678-b071-03342b6c7f91","meta":{"loaded":null,"created":"2016-11-18T23:18:43.576921Z"},"type":"device-configuration"}]}'
    http_version: '1.1'
    adapter_metadata:
      effective_url: https://api.helium.com/v1/element/56618098-5145-445c-a6db-805eaf37ff51/device-configuration
  recorded_at: Mon, 21 Nov 2016 17:31:58 GMT
recorded_with: VCR 3.0.3
